
name: lyam_interactive_app
description: A humanized assistant app.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.2.0
  flutter_tts: ^3.8.5
  lottie: ^2.7.0
  firebase_core: ^2.22.0
  firebase_database: ^10.3.4
  mqtt_client: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/neutral_character.json
    - assets/happy_character.json
    - assets/angry_character.json
